# Generated by Django 5.2.5 on 2025-12-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=254, unique=True)),
                ('customer_number', models.IntegerField()),
                ('password', models.CharField(max_length=225)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Waiter',
            fields=[
                ('waiter_id', models.AutoField(primary_key=True, serialize=False)),
                ('waiter_name', models.CharField(max_length=100)),
                ('waiter_number', models.IntegerField()),
                ('waiter_email', models.EmailField(max_length=254, unique=True)),
                ('waiter_shift', models.CharField(choices=[('morning', 'Morning Shift'), ('evening', 'Evening Shift'), ('night', 'Night Shift')], max_length=20)),
                ('password', models.CharField(max_length=255)),
                ('joined_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
