# Generated by Django 5.2.5 on 2025-12-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urban_umami', '0002_subcategory_menuitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('res_id', models.AutoField(primary_key=True, serialize=False)),
                ('cus_name', models.CharField(max_length=100)),
                ('cus_email', models.EmailField(max_length=254)),
                ('res_date', models.DateField()),
                ('res_time', models.TimeField()),
                ('num_people', models.PositiveIntegerField()),
            ],
        ),
    ]
