# Generated by Django 5.2.5 on 2025-12-15 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urban_umami', '0003_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('order', models.CharField(blank=True, max_length=255)),
                ('food_rating', models.PositiveSmallIntegerField(choices=[(5, '★★★★★ Excellent'), (4, '★★★★ Very Good'), (3, '★★★ Good'), (2, '★★ Average'), (1, '★ Poor')])),
                ('service_rating', models.PositiveSmallIntegerField(choices=[(5, '★★★★★ Excellent'), (4, '★★★★ Very Good'), (3, '★★★ Good'), (2, '★★ Average'), (1, '★ Poor')])),
                ('ambience_rating', models.PositiveSmallIntegerField(choices=[(5, '★★★★★ Excellent'), (4, '★★★★ Very Good'), (3, '★★★ Good'), (2, '★★ Average'), (1, '★ Poor')])),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
