# Generated by Django 5.2.5 on 2026-03-23 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urban_umami', '0005_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='waiter',
            name='waiter_number',
            field=models.CharField(max_length=15),
        ),
    ]
